`default_nettype none
`define WORD_WIDTH 32
`define DECODER_MEM_ADDR_WIDTH 6
`define DECODER_MEM_DATA_WIDTH 8
`define DECODER_MEM_DATA_DEPTH 64
`define STACK_MEM_ADDR_WIDTH 8
`define STACK_MEM_DATA_WIDTH 32
`define STACK_MEM_DATA_DEPTH 256
`define INSTR_WIDTH 16
